services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: uploads
      POSTGRES_USER: uploads
      POSTGRES_PASSWORD: uploads
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  localstack:
    image: localstack/localstack:3.8.1
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-central-1
      - DEBUG=0
    ports:
      - "4566:4566"
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"

volumes:
  pgdata: {}
